name: Eleventy Build
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Compile
        uses: elstudio/actions-js-build/build@v2
        with:
          args: run deploy
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
